### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by apollo13** [PagerDuty/go-pdagent#12]
Hi there, we are currently evaluating whether we could switch to the go agent and wondering when it will leave beta status and be promoted to a full alternative for the existing agent.

**Comment by bzmw** [comment]
Hey there!
We are still looking at further developing this. 

If you see feature value in switching from the python agent to the go agent I would do it. But if you see no value I would say stick with the python agent until we officially promote this to recommended agent.

**Comment by ChezCrawford** [comment]
@apollo13 : As @bzmw mentioned above, this project is still alive!  We have been doing some shuffling around and there has been a bit of delay in development here but it is still part of our plan to officially launch this agent and deprecate our current [pdagent](https://github.com/PagerDuty/pdagent).

The core of this project is fairly complete.  The missing items are mainly around integration with specific tools like Nagios, Sensu, etc.  Please let us know if you start using it and have any feedback.
